name: Generate Curled Test Data Spreadsheets
permissions: write-all
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  synthetic-record-generator:
    name: Generate and Push Curled Test Data Spreadsheets
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment
        env:
          BUILD_TRIGGER: ${{ github.event_name }}
        run: |
          echo "BUILD_TRIGGER=${BUILD_TRIGGER}" | tee -a ${GITHUB_ENV}
          if [ "${BUILD_TRIGGER}" == "push" ] || [ "${BUILD_TRIGGER}" == "workflow_dispatch" ]
          then
            RELEASE="true"
          fi
          echo "RELEASE=${RELEASE:-false}" | tee -a ${GITHUB_ENV}
      - name: Install libreoffice
        run: |
          sudo apt install -y --no-install-recommends libreoffice
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}
      - name: Generate spreadsheets
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          CHAPI_CCG_CLIENT_ID: ${{ secrets.CHAPI_CCG_CLIENT_ID }}
          CHAPI_CCG_CLIENT_SECRET: ${{ secrets.CHAPI_CCG_CLIENT_SECRET }}
          CHAPI_CCG_AUDIENCE: ${{ secrets.CHAPI_CCG_AUDIENCE }}
          CHAPI_CCG_OAUTH_URL: ${{ secrets.CHAPI_CCG_OAUTH_URL }}
          MAGIC_PATIENT_ICN: ${{ secrets.MAGIC_PATIENT_ICN }}
        run: |
          echo "Release: ${RELEASE}"
          for template in $(find src/resources -name '*-template.json' -type f)
          do
            apiName=$(basename "${template}" | sed 's/-template.json//')
            mkdir --parents "${apiName}"
            ./src/scripts/generate-test-patient-spreadsheets.sh "${template}" "${apiName}/${apiName}-test-patient-data.xlsx"
          done
      - name: Upload Spreadsheets
        env:
          GH_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          cd ${GITHUB_WORKSPACE}/consumer-docs
          git config user.name libertybot
          git config user.email "<none>"
          CHANGES=$(git status --untracked-files=no --porcelain)
          if [ -z "${CHANGES:-}" ]
          then
            echo "No changes"
            exit 0
          fi
          echo "Pushing updated spreadsheets"
          git commit -m "Updated synthetic data spreadsheets"
          git push -u origin ${BRANCH_NAME}
